### ISSUE TITLE
Error with mpd 0.20.6

### ISSUE THREAD

**Issue by kitt-cat** [vincent-petithory/mpdfav#4]
When I attempt to vote up a file I get the following:

`2017/06/17 21:47:18.973568 playlistgenerator.go:45: Invalid input: Modified, expected sticker`

Full output:

```
2017/06/17 21:47:11.771644 mpdfavd.go:84: Started Playcounts service...
2017/06/17 21:47:11.771816 mpdfavd.go:88: Started Ratings service...
2017/06/17 21:47:18.500980 ratings.go:113: Ratings: incoming message {ratings +}
2017/06/17 21:47:18.781209 ratings.go:132: Ratings: Brandenburg Concerto No. 1 in F major BWV 1046 rating=1
2017/06/17 21:47:18.781316 playlistgenerator.go:38: playlist generator: regenerating Best Rated
2017/06/17 21:47:18.973568 playlistgenerator.go:45: Invalid input: Modified, expected sticker
panic: Invalid input: Modified, expected sticker

goroutine 28 [running]:
log.Panic(0xc420036df0, 0x1, 0x1)
	/usr/lib/go/src/log/log.go:322 +0xc0
main.generatePlaylist(0xc420084280, 0x584947, 0x6, 0xc4200707b0, 0xa, 0x32, 0x101)
	/home/gandalf3/.cache/pacaur/mpdfav-git/src/src/github.com/vincent-petithory/mpdfav/mpdfavd/playlistgenerator.go:45 +0x234
main.generateBestRatedSongs.func1(0xc42006eba6, 0x55, 0x584947, 0x6, 0xc4200714a8, 0x1)
	/home/gandalf3/.cache/pacaur/mpdfav-git/src/src/github.com/vincent-petithory/mpdfav/mpdfavd/playlistgenerator.go:62 +0x5e
main.ListenSongStickerChange(0xc42006e720, 0xc4200750e0)
	/home/gandalf3/.cache/pacaur/mpdfav-git/src/src/github.com/vincent-petithory/mpdfav/mpdfavd/playlistgenerator.go:33 +0xe2
main.startMpdService.func1(0xc4200707d0, 0xc42006e720, 0xc4200750e0)
	/home/gandalf3/.cache/pacaur/mpdfav-git/src/src/github.com/vincent-petithory/mpdfav/mpdfavd/mpdfavd.go:48 +0x5b
created by main.startMpdService
	/home/gandalf3/.cache/pacaur/mpdfav-git/src/src/github.com/vincent-petithory/mpdfav/mpdfavd/mpdfavd.go:49 +0x13b
```

**Comment by tmplt** [comment]
This issue applies to mpd 0.20.15 also.

**Comment by cotko** [comment]
I just tried it today and it's failing for me too, also for .25.15 :/

**Comment by Spheerys** [comment]
I have the problem too with Music Player Daemon 0.20.18 :(
It's look like the mpd sticker call changed for a while... 
@vincent-petithory : are you still there to have a look ?
